spring:
  application:
    name: experian-integracion
  
  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        ddl-auto: validate

server:
  port: 6001
  
app:
  kafka:
    topics:
      webhook-events: experian.webhook.events
      descarga-orden: documento.descarga.orden
      descarga-resultado: documento.descarga.resultado